from src.dialogue.dialogueobject import *

default = Dialogue([
    DialogueBox("sprites/players/missioncontrol.png", "time to start the real mission, here’s the overview"),
    DialogueBox("sprites/players/missioncontrol.png","this building in front of you belongs to the evil organization known as ‘MORA’. We have reason to believe that inside there's the outline for something big. Your mission is to break in and take it so we can get an idea of what they're planning."),
    DialogueBox("sprites/players/catdoubt.png", "don't sound very sure of yourself huh"),
    DialogueBox("sprites/players/missioncontrol.png", "what do you mean"),
    DialogueBox("sprites/players/catdoubt.png","we have “reason” to “believe” there's an “outline” for “something”, we needed gat it to get an “idea”"),
    DialogueBox("sprites/players/missioncontrol.png","all right, all right, I get it. listen that’s just what’s written here, i didn’t write the script, okay?"),
    DialogueBox("sprites/players/catdialogue.png", "script? you make it sound like we’re in a movie or something"),
    DialogueBox("sprites/players/axolotldialogue.png", "or a game"),
    DialogueBox("sprites/players/catdialogue.png", "heck ya, like a really cool video game "),
    DialogueBox("sprites/players/missioncontrolmad.png", "THIS IS NOT A GAME, TAKE THIS SERIOUSLY GUYS"),
    DialogueBox("sprites/players/catdialogue.png", "what do you think is the most epic way to get in the building?"),
    DialogueBox("sprites/players/axolotldialogue.png", "front door"),
    DialogueBox("sprites/players/catdialogue.png", "YES, TO THE FRONT DOOR"),
    DialogueBox("sprites/players/missioncontrol!.png", "WAIT"),
    DialogueBox("sprites/players/catlookotherway.png", "what"),
    DialogueBox("sprites/players/missioncontrolmad.png","you will NOT be going through the front door, you'll be going up the side of the building to get to the top level"),
    DialogueBox("sprites/players/axolotldialogue.png", "sounds boring"),
    DialogueBox("sprites/players/missioncontrol.png","well to bad, you will go up the side of the building, and if anyone asks you two are just window cleaners, okay?"),
    DialogueBox("sprites/players/catdialogue.png", "fine"),
    DialogueBox("sprites/players/axolotldialogue.png", "what do we do if they ask about our guns?"),
    DialogueBox("sprites/players/axolotldialogue.png", "the ones that we can shoot by pressing left click or right bumper on the controller?"),
    DialogueBox("sprites/players/axolotldialogue.png", "and that helps us gets over walls we couldn't get over otherwise, by shooting each other over as a neat and interesting concept for a platforming game?"),
    DialogueBox("sprites/players/catdoubt.png", "what"),
    DialogueBox("sprites/players/missioncontrol.png", "what"),
    DialogueBox("sprites/players/missioncontrol.png", "just dont show your guns if they ask you"),

])
random_window = Dialogue([
    DialogueBox("sprites/players/racoondialoguehat.png", "we gotta invest in this stuff early"),
    DialogueBox("sprites/players/racoondialoguebow.png", "but the boss said not to spend money on this"),
    DialogueBox("sprites/players/racoondialoguehat.png", "we are not spending we’ll be making"),
    DialogueBox("sprites/players/missioncontrol!.png", "investing?"),
    DialogueBox("sprites/players/missioncontrol.png", "wait, wait, go back, lets find out what that was"),
    DialogueBox("sprites/players/racoondialoguemonocle.png", "well these graphics are very professional and everything but…"),
    DialogueBox("sprites/players/racoondialoguehat.png", "what’s there to talk about? it’s a good offer, we take and make lots of money"),
    DialogueBox("sprites/players/racoondialoguebow.png", "the boss would like that"),
    DialogueBox("sprites/players/missioncontrol.png", "invest in what, come on…"),
    DialogueBox("sprites/players/racoondialoguewatch.png", "let’s do a vote, all in favor?"),
    DialogueBox("sprites/players/racoondialoguemonocle.png", "all right then it’s decided"),
    DialogueBox("sprites/players/missioncontrol.png", "come on come on"),
    DialogueBox("sprites/players/racoondialoguemonocle.png", "we will invest 1 million in 'Trash Distribution for World Domination Incorporated'"),
    DialogueBox("sprites/players/racoondialogue.png", "all: YAY"),
    DialogueBox("sprites/players/missioncontroldrop.png", "huh"),
    DialogueBox("sprites/players/axolotldialogue.png", "well?"),
    DialogueBox("sprites/players/missioncontrol.png", "interesting, i've heard of them, they're new and were looking for investors, didn’t think they'd manage this."),
    DialogueBox("sprites/players/catdialogue.png", "so like are we going to do something"),
    DialogueBox("sprites/players/missioncontrol.png", "not right now, you have more important stuff to do. we’ll save this for later"),
    DialogueBox("sprites/players/catdialogue.png", "maybe we should invest, looks like it’s going to make a lot"),
    DialogueBox("sprites/players/missioncontrol!!.png", "WHAT?!?!?!?!?"),
    DialogueBox("sprites/players/missioncontrolmad.png", "IT’S A EVIL ORGANIZATION, WE CAN’T INVEST IN THAT")
])

end = Dialogue([
    DialogueBox("sprites/players/racoondialoguetie.png", "who are you guys? how'd you get in here?"),
    DialogueBox("sprites/players/catscared.png", "uh..."),
    DialogueBox("sprites/players/axolotldialogue.png", "window cleaners"),
    DialogueBox("sprites/players/racoondialoguetie.png", "oh i see, come to think of it we haven’t cleaned these windows in a long time"),
    DialogueBox("sprites/players/racoondialoguetie.png", "but um.. where are your tools?"),
    DialogueBox("sprites/players/catsmalleye.png", "uh, right here"),
    DialogueBox("sprites/players/catsmalleye.png", "*shows gun*"),
    DialogueBox("sprites/players/missioncontrol!!.png", "?!?!WHAT ARE YOU DOING"),
    DialogueBox("sprites/players/racoondialoguetie.png", "?"),
    DialogueBox("sprites/players/racoondialoguetie.png", "isn’t that a gun?"),
    DialogueBox("sprites/players/catdialogue.png", "yes, a window cleaning gun"),
    DialogueBox("sprites/players/racoondialoguetie.png", "you sure?"),
    DialogueBox("sprites/players/missioncontroldrop.png", "oh no"),
    DialogueBox("sprites/players/catdialogue.png", "yep, a gun for cleaning"),
    DialogueBox("sprites/players/axolotldialogue.png", "windows"),
    DialogueBox("sprites/players/catlookotherway.png", "yes, windows, for cleaning widows"),
    DialogueBox("sprites/players/racoondialoguetie.png", "…"),
    DialogueBox("sprites/players/catdoubt.png", "specifically windows"),
    DialogueBox("sprites/players/racoondialoguetie.png", "really? cuz it looks like a normal gun to me, you sure"),
    DialogueBox("sprites/players/missioncontroldrop.png", "not good"),
    DialogueBox("sprites/players/catdialogue.png", "yep"),
    DialogueBox("sprites/players/racoondialoguetie.png", "oh"),
    DialogueBox("sprites/players/racoondialoguetie.png", "cool"),
    DialogueBox("sprites/players/missioncontrol!!.png", "?!?"),
    DialogueBox("sprites/players/racoondialoguetie.png", "well in that case ill get out of your way, for a secret evil organization we have a lot windows"),
    DialogueBox("sprites/players/missioncontrol.png", "how the..."),
    DialogueBox("sprites/players/catdialogue.png", "you did say that if any one asked that we were window cleaners"),
    DialogueBox("sprites/players/missioncontrollines.png", "whatever, just get the files")

])
dialogues = {
    "default": default,
    "random_window": random_window,
    "enddialogue": end
}
